ERROR - 2023-10-09 03:32:40 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\crud\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\crud\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'concessionaria', 3306, '', 0)
#1 C:\xampp\htdocs\crud\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\crud\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\crud\system\Database\BaseBuilder.php(1748): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\crud\app\Controllers\Home.php(14): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#5 C:\xampp\htdocs\crud\system\CodeIgniter.php(919): App\Controllers\Home->login()
#6 C:\xampp\htdocs\crud\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\crud\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\crud\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\crud\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\crud\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\crud\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\crud\system\Database\BaseBuilder.php(1748): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\crud\app\Controllers\Home.php(14): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#4 C:\xampp\htdocs\crud\system\CodeIgniter.php(919): App\Controllers\Home->login()
#5 C:\xampp\htdocs\crud\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\crud\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\crud\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-09 03:32:40 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1748): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`
WHERE `nome_usuario` = :nome_usuario:
AND `senha_usuario` = :senha_usuario:', [...], false)
 3 APPPATH\Controllers\Home.php(14): CodeIgniter\Database\BaseBuilder->getWhere([...])
 4 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->login()
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-09 06:22:25 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 246.
 1 SYSTEMPATH\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-10-09 06:22:26 --> Uncaught Error: Class "Locale" not found in C:\xampp\htdocs\crud\system\Helpers\number_helper.php:136
Stack trace:
#0 C:\xampp\htdocs\crud\system\Helpers\number_helper.php(55): format_number(4.0, 2, NULL, Array)
#1 C:\xampp\htdocs\crud\system\Debug\BaseExceptionHandler.php(145): number_to_size(4.0, 2)
#2 C:\xampp\htdocs\crud\app\Views\errors\html\error_exception.php(360): CodeIgniter\Debug\BaseExceptionHandler::describeMemory(4194304)
#3 C:\xampp\htdocs\crud\system\Debug\BaseExceptionHandler.php(241): include('C:\\xampp\\htdocs...')
#4 C:\xampp\htdocs\crud\system\Debug\BaseExceptionHandler.php(244): CodeIgniter\Debug\BaseExceptionHandler->CodeIgniter\Debug\{closure}()
#5 C:\xampp\htdocs\crud\system\Debug\ExceptionHandler.php(109): CodeIgniter\Debug\BaseExceptionHandler->render(Object(CodeIgniter\Exceptions\FrameworkException), 500, 'C:\\xampp\\htdocs...')
#6 C:\xampp\htdocs\crud\system\Debug\Exceptions.php(146): CodeIgniter\Debug\ExceptionHandler->handle(Object(CodeIgniter\Exceptions\FrameworkException), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\FrameworkException))
#8 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\FrameworkException
The framework needs the following extension(s) installed and loaded: intl.
#0 C:\xampp\htdocs\crud\system\CodeIgniter.php(246): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
#1 C:\xampp\htdocs\crud\system\CodeIgniter.php(210): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
#2 C:\xampp\htdocs\crud\public\index.php(67): CodeIgniter\CodeIgniter->initialize()
#3 {main}
in SYSTEMPATH\Helpers\number_helper.php on line 136.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2023-10-09 04:23:40 --> mysqli_sql_exception: Table 'concessionaria.usuario' doesn't exist in engine in C:\xampp\htdocs\crud\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\crud\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\crud\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\crud\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\crud\system\Database\BaseBuilder.php(1748): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\crud\app\Controllers\Home.php(14): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#5 C:\xampp\htdocs\crud\system\CodeIgniter.php(919): App\Controllers\Home->login()
#6 C:\xampp\htdocs\crud\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\crud\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\crud\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-09 04:23:40 --> Table 'concessionaria.usuario' doesn't exist in engine
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1748): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`
WHERE `nome_usuario` = :nome_usuario:
AND `senha_usuario` = :senha_usuario:', [...], false)
 2 APPPATH\Controllers\Home.php(14): CodeIgniter\Database\BaseBuilder->getWhere([...])
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->login()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 04:27:57 --> mysqli_sql_exception: Table 'concessionaria.usuario' doesn't exist in engine in C:\xampp\htdocs\crud\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\crud\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\crud\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\crud\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\crud\system\Database\BaseBuilder.php(1748): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\crud\app\Controllers\Home.php(14): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#5 C:\xampp\htdocs\crud\system\CodeIgniter.php(919): App\Controllers\Home->login()
#6 C:\xampp\htdocs\crud\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\crud\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\crud\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-09 04:27:57 --> Table 'concessionaria.usuario' doesn't exist in engine
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1748): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`
WHERE `nome_usuario` = :nome_usuario:
AND `senha_usuario` = :senha_usuario:', [...], false)
 2 APPPATH\Controllers\Home.php(14): CodeIgniter\Database\BaseBuilder->getWhere([...])
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->login()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-09 05:03:07 --> mysqli_sql_exception: Table 'concessionari.usuario' doesn't exist in engine in C:\xampp\htdocs\crud\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\crud\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\xampp\htdocs\crud\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\crud\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\crud\system\Database\BaseBuilder.php(1748): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\crud\app\Controllers\Home.php(14): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#5 C:\xampp\htdocs\crud\system\CodeIgniter.php(919): App\Controllers\Home->login()
#6 C:\xampp\htdocs\crud\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\crud\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\crud\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-10-09 05:03:07 --> Table 'concessionari.usuario' doesn't exist in engine
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1748): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`
WHERE `nome_usuario` = :nome_usuario:
AND `senha_usuario` = :senha_usuario:', [...], false)
 2 APPPATH\Controllers\Home.php(14): CodeIgniter\Database\BaseBuilder->getWhere([...])
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\Home->login()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
